### PR TITLE
Added API for Add/Update Organization Membership. Refs[#238]

### PR DESCRIPTION
**Pull request by Shwetakale**
+ https://developer.github.com/v3/orgs/members/#add-or-update-organization-membership end point was missing in this Gem. Added grant_organization_membership method for this in orgs section.

 + example
     
```ruby
    github = Github.new oauth_token: '...'
    github.orgs.members.grant_organization_membership 'org-name', 'member-name', {role: 'role'}
```
+    role is optional and can be member / admin. default - member

### CODE REVIEW

**Comment by Shwetakale** [comment]
@peter-murach I added my credentials while testing this API locally to generate cassettes and they are passing locally but travis is failing. 

What should I do to pass this build on travis?

**Comment by phoet** [comment]
@Shwetakale thx for implementing this.

i think you made a small mistake where `<BASIC_AUTH>` should be `https://<BASIC_AUTH>` in the first casette.

**Comment by Shwetakale** [comment]
@phoet Yup looks like. Thanks updated this PR :).

**Comment by phoet** [comment]
@Shwetakale there is a test failing just for the jruby test-suite. i'm assuming that there is an issue with the order of `let` and `before` in the `grant_organization_membership_spec.rb`.

i'd try moving the mock-request calls down into the describe blocks. there is also a `after { reset_authentication_for(subject) }` in the other spec files. don't know exactly if that is of interest here.

**Comment by Shwetakale** [comment]
@phoet Thanks. You are right Test case is only failing for JRuby and I don't think any issue of let and before filter. Will need test it on JRuby.

**Comment by peter-murach** [comment]
Thank you!

**Pull request merged**
