### PR TITLE
Add support to specify upload endpoint

### LINKED ISSUE #259: Upload endpoint hardcoded - doesn't work with Github Enterprise
Facing an issue when trying to upload asset to enterprise Github of my company. Digging down it appears that the upload endpoint is hardcoded:

https://github.com/peter-murach/github/blob/master/lib/github_api/client/repos/releases/assets.rb#L73

Is it possible to move it out to the config ? Something like `c.upload_endpoint` ?

### PR DESCRIPTION
**Pull request by shadabahmed**
Fixes #259

### CODE REVIEW

**Comment by shadabahmed** [comment]
No idea why the travis build is failing here while is built successfully for the same commit on my fork :cry:

**Comment by shadabahmed** [comment]
Fixed now.  Please review travis.yml as well

**Comment by peter-murach** [comment]
Hi Shadab, thanks a ton! I've released new version `v0.13.1` that includes your patch.

**Comment by shadabahmed** [comment]
Thanks to you too. Already using `v0.13.1` now :+1:

**Pull request merged**
