### PR TITLE
Implement support for the X-RateLimit-Reset header

### PR DESCRIPTION
**Pull request by k0nserv**

### CODE REVIEW

**Comment by k0nserv** [comment]
ping @peter-murach

**Comment by peter-murach** [comment]
@k0nserv I will release tomorrow - promise! I need to triage all the issues and PRs and will then will release. Can you wait?

**Comment by k0nserv** [comment]
Oh I wasn't pinging you to release. I merely want to know if it's okay to merge. Release whenever you get the time

**Comment by peter-murach** [comment]
The code is spot on, will definitely merge!

**Pull request merged**
